### ISSUE TITLE
Can you add a successful and failed callback?

### ISSUE THREAD

**Issue by baijunjie** [oblador/react-native-store-review#12] opened 2017-10-16 13:01 UTC
Great plugins！
But the popup scoring view has network latency, I need to know when it will be displayed, or because it will fail for a silent reason and give the user friendly hints.

**Comment by oblador** [comment] 2017-10-23 17:34
Duplicate of https://github.com/oblador/react-native-store-review/issues/9 et al

**Closed as completed by oblador** 2017-10-23 17:34 UTC
