### ISSUE TITLE
App crashes when requesting for review

### ISSUE THREAD

**Issue by watadarkstar** [oblador/react-native-store-review#49] opened 2021-03-11 20:49 UTC
**Description**

I was testing this library using the Xcode simulator and it was working. But after showing the alert a bunch of times the app is now unusable after calling `StoreReview.requestReview()`. 

**Reproduction**

1. Open app in simulator
2. Repeat this a bunch of times until the app becomes unusable

**Code**

```jsx
import { useEffect } from 'react'
import * as StoreReview from 'react-native-store-review'

export default function AppReview() {
  /* Open app review alert */
  useEffect(() => {
    // This API is only available on iOS >= 10.3 or Android API >= 21
    if (StoreReview.isAvailable) {
      StoreReview.requestReview()
    } 
  }, [])
  return null
}
```

**Version**

    "react-native-store-review": "^0.2.0",
    "react-native": "0.63.4",

**Comment by oblador** [comment] 2021-03-11 23:04
Can you reproduce this on device?

**Comment by watadarkstar** [comment] 2021-03-11 23:06
@oblador I wasn't able to reproduce it on a device. 

As a workaround for anyone who runs into this. I had to quit the simulator and re-run the app in Xcode.

**Comment by oblador** [comment] 2021-03-16 17:05
I'm going to close this as I don't really see how it's caused by this module. Maybe it's a bug in the simulator.

**Closed as completed by oblador** 2021-03-16 17:05 UTC
